import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Login from '../src/components/Login'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ALVlN CNAT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <div>
        <h1>
          FAÇA LOGIN AGORA!!
        </h1>
      </div>
      <div>
        <Login>
          
        </Login>
      </div>

    </div>
    
  )
}
